### ISSUE TITLE
Add pagination to transaction history view

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1652]
Steps:

1. Login to account that have a lot of transactions (example private key for testnet: 56ECDB91928CFBBE274B90124BDB68C424DC8A079E60FD5DD0A37968CCC3B7B2)

2. Go to Home -> History

Current result:
Wallet load all confirmed transactions which makes it not responsible if account has many transactions.

Expected result:
Wallet load only transactions that are currently visible on view.

**Comment by coiki** [comment]
### User Story
As a user that has made transactions with my wallet,
I want to see my recent relevant transactions quickly, and have the ability to browse through my entire history when I need to,
so I can understand what mosaics have come in and out of my wallet.

### Solution
Implement pagination to the API call (if not available) and screen of the Transaction History View.

### Acceptance Criteria
**AC1.** When I enter the Transaction History View I can see the 10 most recent transactions.
**AC2.** When I click on the "See more" link, the next 20 transactions load. They will keep loading 20 by 20.
**AC3.** When I have reached the end of the list, a text "End of History" will be shown instead of "See more" link.

**Comment by coiki** [comment]
Implementation might be infinite scroll rather than "See more" button. Depending on if we can find the work that was done previously.

**Comment by cryptoBeliever** [comment]
Fixed in dev :+1:
