### ISSUE TITLE
Explorer - URL tied to profile

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1766]
Currently, when we change the URL for explorer for old profiles old URL stays.

Why it's saved on profile level? To allow edit it? @coiki do you think anyone is using this option?

My propositions:
- remove the possibility to edit explore link **or**
- provide versioning. If the version increases then overwrite URL stored on profile level with current one.

![image](https://user-images.githubusercontent.com/17684281/141356880-3c0e7906-5aed-43ca-9a0b-4f2d19ece3c4.png)

@coiki what you think about that?

**Comment by coiki** [comment]
@cryptoBeliever I agree that this makes more sense at client-level (in the app) rather than at profile level. 

Are we sure other products don't have dependency on this? If it's only local let's remove it from here and send it to settings.

For the existing URLs I would push for a migration in the next release. Let's start with letting the community know about the good practice of keeping that URL up-to-date.

**Comment by cryptoBeliever** [comment]
Fixed in PR #1775
