### ISSUE TITLE
Error login - when selected node websockets doesn't work

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1767]
Looks like it's issue with nodes that don't support webscockets or websockets doesn't work. 

Steps to reproduce:
1. Create profile and connect to node X
2. Close app
3. Shut down node X
4. Open app and login
5. App will detect that node X is down and will switch to other node Y

If node Y will be without working WebSockets user will be not able to login (error below) each time.

Steps to reproduce (easier way for developer):
1. Create profile on mainnet (can be on browser version because it's easier to change local storage data)
2. Open chrome console go to Application -> Local storage -> profiles. Change for profile selectedNodeUrlToConnect to (for example) https://0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-4.symbol-nodes.jp:3001/
3. Close chrome console and try login. Each time failed (for 0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-4.symbol-nodes.jp node WebSockets doesn't work).

![image](https://user-images.githubusercontent.com/17684281/141453587-0b87e341-47c5-49d3-aec1-819281ce9a85.png)

**Workaround for users**:
- **If user have mnemonics (24 words) backup**: Try create a new profile using mnemonics (24 words) backup. Create a new profile -> Import mnemonics. It should connect to random node which hopefully will have working websockets.
- **If user don't have mnemonics backup**. User should wait until the new version released. 

Also if node has disabled wss web sockets but enabled HTTPS user is not able switch to this node:

![image](https://user-images.githubusercontent.com/17684281/141642871-8d840b33-eac1-4014-a38b-d9df6c376805.png)

**Comment by yilmazbahadir** [comment]
Some of the nodes don't have the websocket on `wss` (secured) and that's the root cause I believe.

![image](https://user-images.githubusercontent.com/6256269/141525454-52d4efaf-5108-49de-9907-806b20e6581d.png)

You can use the below steps to test it.
1. install the `wscat` npm package globally. 
```
npm install -g wscat
```
2. try to connect (secure)
```
wscat -c "wss://NODE_URL:3001/ws"
```
3. try to connect (insecure)
```
wscat -c "ws://NODE_URL:3000/ws"
```

Some of the https enabled node URL's to check:

- _wolf.importance.jp , status: unable to connect via wss:3001 , ws:3000 works_
- _0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-4.symbol-nodes.jp , status: unable to connect via wss:3001 , ws:3000 works_
- 0-0-0-0-5.supreme-harvest-node.gym.bond, status: both works
- symbol-harvesting.org, status: both works

**Comment by yilmazbahadir** [comment]
As per the discussions we had with @cryptoBeliever, we now think that this issue happens only in the nodes that manually added `https-portal` configuration to their nodes and not setting `webSocket:true` in their `https-portal` configuration.

In that case, we should be 
1. As a fix in the wallet: falling back to was:3000 when wss:3001 is not available
2. telling the Node Owners to set the `webSocket: true` in their `https-portal` settings OR telling them to use built-in `https-portal` configuration(which is `webSocket: true` by default).

**Comment by cryptoBeliever** [comment]
3. Also, if for some reason ws:3000 will be not available too wallet should use other node instead not allow user to login.

**Comment by NikolaiB** [comment]
@bassemmagdy I have tested it works for me
