### ISSUE TITLE
Namespaces - expired namespaces visible without "Show expired namespaces" checkbox checked

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#873]
On namespaces list by default expired namespaces are presented.

![image](https://user-images.githubusercontent.com/17684281/103707878-c3eea480-4faf-11eb-83ec-9391a03b0898.png)

Expected result: Expired namespace hidden by default and visible only if we check "Show expired namespaces"

**Comment by NikolaiB** [comment]
@bassemmagdy I still can reproduce it 
![image](https://user-images.githubusercontent.com/11311924/121567467-69ff7880-ca40-11eb-8145-ab8ecb9ebafd.png)

**Comment by bassemmagdy** [comment]
@NikolaiB Recheck #1458

**Comment by cryptoBeliever** [comment]
@NikolaiB please retest (I don't own expired namespace on testnet)

**Comment by cryptoBeliever** [comment]
@NikolaiB could you check?

**Comment by NikolaiB** [comment]
@bassemmagdy there are 15 hours left till expiration namespace but it has expired state already 
![image](https://user-images.githubusercontent.com/11311924/125747558-967e40e9-8bd0-45e5-90d9-d2c17093ac61.png)

**Comment by bassemmagdy** [comment]
@NikolaiB since the issue is not testable on our public nodes as the minimum namespace is large enough. I've started a local node to check and it looks like no issues here is a [video](https://www.loom.com/share/12884d1f29034830a4215394929a0a77) also I created a new [branch](https://github.com/symbol/desktop-wallet/commit/2f2a3f5b57e8f94c09dc622889e601ae60c6f135) with custom validation for testing purposes.

**Here are the steps to verify:**

1. install symbol-bootstrap globally and run a local node by default minimum namespace duration is 1 minute. make sure localhost:3000/node/health is up and running
2. connect the node to the wallet.
3. head to `target/nemesis/server-config/block-properties-file.properties`  file on your machine under `[distribution>cat: currency]` section in that file you should find addresses containing funds on your local node, and for the corresponding private keys they are in the `target/addresses.yml` file, import any of them.
4. import any of the private keys into wallet while connected to the local node you should be able to test it.

**Comment by NikolaiB** [comment]
@bassemmagdy @cryptoBeliever fixed
